### ISSUE TITLE
Multi-line tooltip ?

### ISSUE THREAD

**Issue by 0x0L** [yujinakayama/atom-lint#14]
Hi,

HLint spits out long multi-line suggestions.

This patch in `atom-lint.less` allows for multi-line tooltips:

``` css
  .tooltip.bottom .tooltip-inner {
    border-top-left-radius: 0 !important;
    white-space: pre-wrap;
    text-align: left;
  }
```

See my branch x0l:hlint

I am a total css noob, so I don't know if it's the correct way to do this. This is also somehow related to issue #12
